### ISSUE TITLE
Binary Simulation Tool Binee (Remnux 7) - Can we consider adding?

### ISSUE THREAD

**Issue by citizenstaar** [REMnux/salt-states#72]
Reference can be found here:

https://github.com/carbonblack/binee

This is in the binary simulation space.  Thanks.

**Comment by lennyzeltser** [comment]
It's a handy tool. However, I'm having a hard time producing output with it, perhaps because I haven't placed the necessary Windows files under the `os` directory. If you have used this tool earlier, perhaps you can give it a try?

I placed the compiled tool and the Unicorn library it needs [here](https://github.com/REMnux/distro/raw/master/files/binee-amd64.tgz). After you extract it into a directory, go there, then you can run the tool like this:

```
LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH ./binee
```

You'll need to first place the necessary 32-bit Windows 10 files in `os/win10_32/windows/system32` under your current directory.

**Comment by citizenstaar** [comment]
Will post a update soon.  Thanks.

**Comment by citizenstaar** [comment]
It works fine Lenny.  For environment setup for a binary the following steps are useful:

`binee -i`

![image](https://user-images.githubusercontent.com/17726673/87247650-1d23b400-c423-11ea-9c5a-ef6ebb19aabf.png)

Then move the needed dlls from your licensed copy of Windows to the path defaulted to by binee.  
Check for errors and resolve any other needed apis:

`
binee -j ./PE32bit  1>2
binee -j | grep apihere
`
![image](https://user-images.githubusercontent.com/17726673/87247854-45f87900-c424-11ea-9adc-66405ffc4eb1.png)

Perhaps in a future "cheat sheet" you can add that the analyst needs to check the import table and a satisfy all libraries/apis.  Let me know what other proof is needed.  Thank you again for considering this tool.

**Comment by lennyzeltser** [comment]
Thanks for looking into this! Maybe the Windows DLLs I placed in my environment weren't the right versions... strange.

To clarify, before the step in your first screenshot, you already placed the core Windows DLLs into your environment in `os/win10_32/windows/system32`, yes? And then kept adding the other DLLs when taking the steps in your second screenshot?

**Comment by citizenstaar** [comment]
That’s correct...the binary you made expects the 32-bit dlls to be in the current working directory

**Comment by citizenstaar** [comment]
If you are ok with it.:.can you share your sample?

**Comment by lennyzeltser** [comment]
I was just using the 32-bit samples from https://github.com/carbonblack/binee/tree/master/tests.

I placed the 32-bit Windows DLLs in `os/win10_32/windows/system32`, but couldn't get any output besides the date/time stamp and "EOF", though the `-i` parameter does give some visibility:

<img width="1238" alt="image" src="https://user-images.githubusercontent.com/3092125/87251561-94187700-c43a-11ea-8e3f-97b98826d8d1.png">

**Comment by citizenstaar** [comment]
I get errors but its for dlls that I have not made available.  

What happens if you specify the root and point directly at the location of your dlls?  (-r ./os/win10_32/windows/system32/*)

Also, is the hash for test binary this md5: 794712e1422e220305c38298bc6fbbc4

**Comment by lennyzeltser** [comment]
The `-r` didn't make a difference, and based on the difference in error messages when `os` is present and absent, I can tell that the tool is finding the OS files when I place them in `os/win10_32/windows/system32`. I tried this with the sample `794712e1422e220305c38298bc6fbbc4`, but got just the EOF message. BTW, the import table of this sample that I see with `-i` is different from what I saw in your initial screenshot.

Well, my best guess right now is that I've got the wrong Windows DLLs. I'll prepare this package for inclusion with REMnux and hope that people who use the tool will find the right ones. Of course, if you have any further ideas or tips to make this easier or more predictable to use, I'll be glad to hear them.

<img width="963" alt="image" src="https://user-images.githubusercontent.com/3092125/87252100-8533c380-c43e-11ea-9cb4-782a0d9179a2.png">

**Comment by citizenstaar** [comment]
My example was from a tiny downloaded I grabbed off of VT.  Would it make a difference to link it?

I will post some more using local pe tools to determine candidates for analysis using binee.   I will try to grab some malware that meets this usage criteria show where a step might be saved by using this during static analysis. 

I will source samples from VT for the examples.  Let me know if you prefer they be available in a different repo.

**Comment by lennyzeltser** [comment]
Sounds great, thanks!

**Comment by lennyzeltser** [comment]
I added the tool to REMnux. You can get it via `remnux upgrade` or you can just run:

```
sudo apt -y update
sudo apt -y install binee
```

The wrapper around the tool invokes it with the expectation that the 32-bit DLLs are in /opt/binee-files/system32. If you get a chance to test this, I'd love to hear your feedback.

**Comment by PDX4N6** [comment]
Thank you for adding this!  huge addition

**Comment by citizenstaar** [comment]
Lenny if I stage any files in the library directory(/opt/binee-files/system32) I get the following:

![image](https://user-images.githubusercontent.com/17726673/87336391-c1832480-c50f-11ea-99ea-def899da2b14.png)


If I use the -r switch and remove all files from the library directory I can check imports but anything else results in this error:

![image](https://user-images.githubusercontent.com/17726673/87336521-fa22fe00-c50f-11ea-9752-59a582a762d6.png)

At a glance the error is at the same line in the code.  If you want to share some of what you did to package and compile the software maybe I can reproduce on my end.  I did use your tar ball without issue btw (all my prior screen shots are from me using the two binaries you shared).

**Comment by citizenstaar** [comment]
Actually I think I see the issue..stand by...

**Comment by citizenstaar** [comment]
I fixed this by adding the directory: ./os/win10_32/windows/system32/  (using system32 with -r causes crashes)

![image](https://user-images.githubusercontent.com/17726673/87343824-77a03b80-c51b-11ea-974c-2dde24468220.png)


Replacing the binaries with those from your tarball
Then executing directly from inside the directory:
`sudo LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH ./binee  malfile`

The wrapper causes the binee program to ignore all user added switches and you cannot reference a custom location of the libraries

![image](https://user-images.githubusercontent.com/17726673/87343604-22642a00-c51b-11ea-9ca0-09d1988ee463.png)

**Comment by lennyzeltser** [comment]
Thanks! What's the hash of your downloader.exe file?

**Comment by lennyzeltser** [comment]
Also, just to clarify, have you tried invoking the tool without replacing the files, but using the /usr/local/binee command? That wrapper invokes binee with the appropriate parameters and points the tool to /opt/binee-files/system32 for the Windows files. It also lets you override that location with the -r parameter.

**Comment by citizenstaar** [comment]
Downloader is here:  https://www.virustotal.com/gui/file/65a8781449b8e5e800f7601abd48085aa5a6feb73cbd970aab29a33bb36f26be/detection

_"Also, just to clarify, have you tried invoking the tool without replacing the files, but using the /usr/local/binee command?"_
**The binary keeps failing with the errors I linked earlier.  See https://github.com/REMnux/salt-states/issues/72#issuecomment-657703127**
 
_"That wrapper invokes binee with the appropriate parameters and points the tool to /opt/binee-files/system32 for the Windows files. It also lets you override that location with the -r parameter"_

**The wrapper causes all user arguments to be ignored (see my last screen shot with the sudo binee in the command line).  See https://github.com/REMnux/salt-states/issues/72#issuecomment-657741462**

**Comment by lennyzeltser** [comment]
Thanks for the additional details, I'll investigate.

I'm confused why on your system the wrapper is ignoring the arguments. It seems to accept them when I invoke it on my VM, though I haven't yet placed the Windows DLLs anywhere. The intent is for the wrapper to be invoked from anywhere on the system. Also, does the tool need to run with root privileges?

<img width="1495" alt="image" src="https://user-images.githubusercontent.com/3092125/87355421-57c64300-c52e-11ea-82ef-986a1566935e.png">

**Comment by citizenstaar** [comment]
_"Also, does the tool need to run with root privileges?"_
**Just a unnecessary invocation of the command on my part(sudo).  I was testing earlier if there was a issue with permissions and that was not the case.**  

_" It seems to accept them when I invoke it on my VM, though I haven't yet placed the Windows DLLs anywhere."_

**Trying running with specifying the -r and you will get the same errors.**  

_"The intent is for the wrapper to be invoked from anywhere on the system. Also, does the tool need to run with root privileges?"_
Makes sense...I need to experiment more myself to figure out why a shell wrapper is not playing nice with a compiled go binary.  I am out of time today but will certainly poke at this some more later this week.

**Comment by citizenstaar** [comment]
This works fine:

![image](https://user-images.githubusercontent.com/17726673/87362335-56037c00-c53c-11ea-9103-e785ab2c65de.png)

You cannot for some reason use "system32" as the argument for the location of the libraries.  I think this is a binee thing that I will look at next.

**Comment by lennyzeltser** [comment]
Fixed it! There was a minor issue in my wrapper. But more importantly, I didn't realize that the files needed to be not in the top-level directory specified by `-r` but under the windows\system32 structure. Another issue I had the other day was that one of my DLLs was bad.

Ah, the sweet sound of victory. Thanks for your help in trying to figure this out!

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/3092125/87368332-65d68c80-c54b-11ea-9302-617259eea5ca.png">

I haven't released the new state-files package yet, but you can get the new version of this tool now via:

```
sudo apt update -y
sudo apt install -y binee
```

**Comment by citizenstaar** [comment]
Ok...did a fresh rebuild.  Here is what it looks like the "Shell Wrapper" is fine.  The problem is using a folder schema for root that doesn't include the prefix "os".  Proof:
##FAILURE
![image](https://user-images.githubusercontent.com/17726673/87368768-94089c00-c54c-11ea-881a-8faa0c589268.png)


##SUCCESS

![image](https://user-images.githubusercontent.com/17726673/87368808-be5a5980-c54c-11ea-86eb-442cdf19914a.png)

**Comment by citizenstaar** [comment]
Deleted my last post...ok will retest.  That's right.

**Comment by citizenstaar** [comment]
Ok...its still not working.  Here is what does work:

![image](https://user-images.githubusercontent.com/17726673/87369167-d5e61200-c54d-11ea-9d78-16a4c0be4bcb.png)

Permissions:

![image](https://user-images.githubusercontent.com/17726673/87369190-e39b9780-c54d-11ea-8518-137a5f4f7d0b.png)


VS the new install:

![image](https://user-images.githubusercontent.com/17726673/87369329-3f662080-c54e-11ea-9858-5790fd9c4a6d.png)

**Comment by citizenstaar** [comment]
This is working!  Thank you for working through the issue on your end!

**Comment by citizenstaar** [comment]
I can see this creating an issue for someone without specific working knowledge.  Perhaps the following would be appropriate:

- Print a message on usage regarding directory structure of root file system
- Repeat the message regarding the need for licensed access to windows dlls (see the original repo)
- Does the owner need to be root...you have to execute privileged commands to stage the libraries and create subfolders

**Comment by lennyzeltser** [comment]
Good points. I revised the state file to make that win10_32 directory owned by REMnux, so the user won't need root access to manage its structure and contents. I added a note regarding the need for the appropriate structure and DLLs to the documentation site. At some point I hope to create a blog post showcasing the tool for additional guidance.
